---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible OME firmware baseline operations.
  gather_facts: False

  tasks:
  - name: create baseline from device Ids.
    ome_firmware_baseline:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      baseline_name: "baseline_name"
      baseline_description: "baseline_description"
      catalog_name: "catalog_name"
      device_ids:
        - 1010
        - 2020

  - name: create baseline from servicetags.
    ome_firmware_baseline:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      baseline_name: "baseline_name"
      baseline_description: "baseline_description"
      catalog_name: "catalog_name"
      device_service_tags:
        - "SVCTAG1"
        - "SVCTAG2"

  - name: create baseline from device groups.
    ome_firmware_baseline:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      baseline_name: "baseline_name"
      baseline_description: "baseline_description"
      catalog_name: "catalog_name"
      device_group_names:
        - "Group1"
        - "Group2"