---
- hosts: hosts
  connection: local
  name: Export Lifecycle Controller Logs
  gather_facts: False

  tasks:
  - name: Export Lifecycle Controller Logs
    dellemc_export_lc_logs:
       idrac_ip: "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_pwd: "{{ idrac_pwd }}"
       share_name: "{{ playbook_dir }}"
       job_wait: "True"

