---
- hosts: hosts
  connection: local
  name: Import Server Configuration Profile from a Share
  gather_facts: False

  tasks:
  - name: Import Server Configuration Profile from a Share
    dellemc_import_server_config_profile:
       idrac_ip:        "{{ idrac_ip }}"
       idrac_user:      "{{ idrac_user }}"
       idrac_pwd:       "{{ idrac_pwd }}"
       idrac_port:      "{{ idrac_port }}"
       share_name:      "{{ playbook_dir }}"
       scp_file:        "x.x.x.x_20180131_120541_scp.json"
       scp_components:  "NIC"
       shutdown_type:   "Graceful"
       job_wait:        "False"
    
